wondem_application_form.form:
  path: '/application-form'
  defaults:
    _form: '\Drupal\wondem_application_form\Form\ApplicationForm'
    _title: 'Application Form'
  requirements:
    _permission: 'access content'

wondem_application_form.admin_list:
  path: '/admin/content/applications'
  defaults:
    _controller: '\Drupal\wondem_application_form\Controller\ApplicationAdminController::list'
    _title: 'Applications'
  requirements:
    _permission: 'administer site configuration'

wondem_application_form.admin_view:
  path: '/admin/content/applications/{id}'
  defaults:
    _controller: '\Drupal\wondem_application_form\Controller\ApplicationAdminController::view'
    _title: 'Application Details'
  requirements:
    _permission: 'administer site configuration'
  options:
    parameters:
      id:
        type: integer

wondem_application_form.status:
  path: '/application/status'
  defaults:
    _controller: '\Drupal\wondem_application_form\Controller\ApplicationStatusController::status'
    _title: 'Application Status'
  requirements:
    _permission: 'access content'

waf.admin.list:
  path: '/admin/content/applications'
  defaults:
    _title: 'Applications'
    _controller: '\Drupal\wondem_application_form\Controller\ApplicationAdminController::list'
  requirements:
    _permission: 'access administration pages'

waf.admin.review:
  path: '/admin/content/applications/{id}/review'
  defaults:
    _title: 'Review application'
    _form: '\Drupal\wondem_application_form\Form\ApplicationReviewForm'
  requirements:
    _permission: 'access administration pages'
    id: '\d+'

waf.admin.export:
  path: '/admin/content/applications/export'
  defaults:
    _controller: '\Drupal\wondem_application_form\Controller\ApplicationAdminController::exportCsv'
    _title: 'Export applications'
  requirements:
    _permission: 'administer site content'
  options:
    _admin_route: TRUE