views.display.simple_sitemap_export:
  type: views_display
  label: 'Simple XML Sitemap display export options'

views.style.simple_sitemap_export:
  type: views_style
  label: 'Simple XML Sitemap style export options'
  mapping:
    uses_fields:
      type: boolean
      label: 'Whether this style uses fields'
    variants:
      type: sequence
      label: 'Variants'
      sequence:
        type: views_simple_sitemap_export_variant_settings

views_simple_sitemap_export_variant_settings:
  type: mapping
  mapping:
    index:
      label: 'Index'
      type: boolean
    priority:
      label: 'Priority'
      type: string
    changefreq:
      label: 'Change frequency'
      type: string
    arguments:
      label: 'Arguments'
      type: sequence
      sequence:
        type: string
