_core:
  default_config_hash: i-_2TVi6FUEAqBgNRJkt6aaYmiw1k_LTrXzJS6wlZ4U
allowed_types:
  - book
  - policy_procedure_manual_
block:
  navigation:
    mode: 'all pages'
child_type: policy_procedure_manual_
