_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  admin_toolbar: 0
  admin_toolbar_search: 0
  admin_toolbar_tools: 0
  asset_injector: 0
  automated_cron: 0
  big_pipe: 0
  blazy: 0
  block: 0
  block_content: 0
  book: 0
  breakpoint: 0
  carousel: 0
  ckeditor5: 0
  comment: 0
  config: 0
  config_translation: 0
  contact: 0
  content_moderation: 0
  contextual: 0
  ctools: 0
  datetime: 0
  db_maintenance: 0
  dblog: 0
  dynamic_page_cache: 0
  editor: 0
  entity: 0
  entity_reference_revisions: 0
  entity_usage: 0
  faqfield: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  file_delete_ui: 0
  file_mdm: 0
  file_mdm_exif: 0
  file_mdm_font: 0
  filter: 0
  flag: 0
  google_analytics: 0
  gutenberg: 0
  gutenberg_cloud: 0
  help: 0
  history: 0
  image: 0
  image_effects: 0
  imageapi_optimize: 0
  imagemagick: 0
  inline_entity_form: 0
  jquery_ui: 0
  jquery_ui_accordion: 0
  language: 0
  layout_builder: 0
  layout_builder_expose_all_field_blocks: 0
  layout_discovery: 0
  link: 0
  locale: 0
  media: 0
  media_library: 0
  menu_link_content: 0
  menu_ui: 0
  metatag: 0
  metatag_extended_perms: 0
  metatag_hreflang: 0
  metatag_open_graph: 0
  migrate: 0
  migrate_drupal: 0
  migrate_drupal_ui: 0
  mysql: 0
  node: 0
  options: 0
  page_cache: 0
  paragraphs_library: 0
  path: 0
  path_alias: 0
  phpass: 0
  redirect: 0
  responsive_image: 0
  robotstxt: 0
  scheduler: 0
  schema_article: 0
  schema_article_example: 0
  schema_metatag: 0
  schema_movie: 0
  schema_organization: 0
  schema_product: 0
  schema_web_page: 0
  schema_web_site: 0
  search: 0
  search_api: 0
  shortcut: 0
  simple_gmap: 0
  simple_sitemap: 0
  simple_sitemap_views: 0
  sophron: 0
  system: 0
  taxonomy: 0
  telephone: 0
  text: 0
  token: 0
  token_filter: 0
  toolbar: 0
  tour: 0
  update: 0
  user: 0
  video_embed_field: 0
  video_embed_media: 0
  views_ui: 0
  workflows: 0
  yoast_seo: 0
  extlink: 1
  forum: 1
  pathauto: 1
  content_translation: 10
  views: 10
  paragraphs: 11
  standard: 1000
theme:
  claro: 0
  olivero: 0
  stable9: 0
  bootstrap5: 0
profile: standard
