_core:
  default_config_hash: o4bYR9ZupWb3AsOIizTUG4g-nu1mdJqA59UB7QT-ifQ
definitions:
  contact__site_page:
    menu_name: footer
    parent: ''
    weight: 0
    expanded: false
    enabled: true
  user__page:
    menu_name: account
    parent: ''
    weight: -10
    expanded: true
    enabled: true
  search__view:
    enabled: true
    menu_name: tools
    parent: ''
    expanded: false
    weight: 0
