cron_last_run: 1733766791
cron_frequency: 86400
use_time_interval: false
time_interval_start: '01:30'
time_interval_end: '02:30'
all_tables: 1
write_log: 0
_core:
  default_config_hash: T_ds3REH4r3NJRKBQ8cLc-RVnb4uooa-F_oEyWxdB8w
table_list_pantheon: {  }
actions: null
form_build_id: form-1oXyIGY_xeBY3z1UD1kTI9iDUzrGOzkPOTUFKerE-mI
form_token: Yer_vQ21WsOuW88SoUgDtVATNn5UfabPqu_PMb8_tAA
form_id: db_maintenance_admin_settings
