_core:
  default_config_hash: BNxV-YNtK5gSUsFnnvTujYzFdqIHaWxPvvflQNbhuP8
id: security_review-username_same_as_password
skipped: true
skipped_by: 1
skipped_on: 1726010212
settings:
  number_of_users: 100
